[colors.primary]
background = '#1c2023'
foreground = '#c7ccd1'

[colors.cursor]
text = '#1c2023'
cursor = '#c7ccd1'

[colors.normal]
black   = '#1c2023'
red     = '#c7ae95'
green   = '#95c7ae'
yellow  = '#aec795'
blue    = '#ae95c7'
magenta = '#c795ae'
cyan    = '#95aec7'
white   = '#c7ccd1'

[colors.bright]
black   = '#747c84'
red     = '#c7ae95'
green   = '#95c7ae'
yellow  = '#aec795'
blue    = '#ae95c7'
magenta = '#c795ae'
cyan    = '#95aec7'
white   = '#f3f4f5'


[colors.selection]
#TODO


[font]
normal = {family = "Iosevka", style = "Semibold Extended"}
bold = {family = "Iosevka", style = "Extrabold Extended"}
size = 11

[scrolling]
multiplier = 5

[window]
padding = {x = 15, y = 20}

[selection]
save_to_clipboard = true

[cursor]
vi_mode_style = "Beam"
