[buildPlans.IosevkaCode]
family = "Iosevka Code"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaCode.variants]
  inherits = "ss15"

    [buildPlans.IosevkaCode.variants.design]
    one = "base-long-top-serif"
    four = "semi-open-serifed"
    seven = "curly-serifed"
    eight = "crossing"
    nine = "open-contour"
    zero = "oval-reverse-slashed"
    capital-a = "round-top-serifless"
    capital-b = "standard-unilateral-serifed"
    capital-c = "serifless"
    capital-d = "more-rounded-bilateral-serifed"
    capital-e = "serifed-capped"
    capital-f = "top-left-serifed"
    capital-g = "toothed-inward-serifed-hooked"
    capital-h = "top-left-serifed"
    capital-i = "short-serifed"
    capital-j = "flat-hook-serifed-both-sides"
    capital-k = "symmetric-connected-bottom-right-serifed"
    capital-l = "motion-serifed"
    capital-m = "slanted-sides-hanging-motion-serifed"
    capital-n = "standard-motion-serifed"
    capital-p = "closed-motion-serifed"
    capital-q = "detached-bend-tailed"
    capital-r = "curly-top-left-serifed"
    capital-s = "unilateral-serifed"
    capital-t = "motion-serifed"
    capital-u = "toothed-motion-serifed"
    capital-v = "curly-motion-serifed"
    capital-w = "straight-motion-serifed"
    capital-x = "straight-bilateral-motion-serifed"
    capital-y = "straight-motion-serifed"
    capital-z = "curly-bottom-serifed"
    a = "single-storey-tailed"
    e = "rounded"
    f = "tailed"
    g = "double-storey-open"
    h = "straight-top-left-serifed"
    i = "serifed-flat-tailed"
    k = "curly-top-left-serifed"
    l = "tailed-serifed"
    m = "short-leg-tailed-top-left-serifed"
    n = "tailed-motion-serifed"
    p = "eared-motion-serifed"
    q = "earless-rounded-tailed-serifless"
    r = "corner-hooked-serifless"
    s = "unilateral-serifed"
    t = "bent-hook-asymmetric-short-neck"
    u = "toothed-motion-serifed"
    v = "cursive-serifed"
    w = "curly-almost-flat-top-motion-serifed"
    x = "semi-chancery-curly-serifless"
    y = "straight-turn-motion-serifed"
    z = "cursive"
    cyrl-u = "cursive-flat-hook-serifless"
    cyrl-yeri = "cursive"
    asterisk = "penta-high"
    ascii-grave = "straight"
    ascii-single-quote = "raised-comma"
    paren = "flat-arc"
    brace = "straight"
    number-sign = "slanted"
    ampersand = "closed"
    at = "fourfold"
    percent = "rings-continuous-slash-also-connected"

  [buildPlans.IosevkaCode.ligations]
  inherits = "clike"

[buildPlans.IosevkaCode.widths.Condensed]
shape = 456
menu = 3
css = "condensed"

[buildPlans.IosevkaCode.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCode.widths.SemiCondensed]
shape = 548
menu = 4
css = "semi-condensed"

[buildPlans.IosevkaCode.widths.SemiExtended]
shape = 658
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaCode.widths.Extended]
shape = 720
menu = 7
css = "expanded"

[buildPlans.IosevkaCode.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCode.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
